# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test module
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Build & Test module (with host toolchain)
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  build_and_test_host:
    # Starting with Ubuntu 24.04 apparmor breaks Bazels linux-sandbox: https://github.com/bazelbuild/bazel/issues/24081
    runs-on: ubuntu-22.04
    steps:
      - name: Clean up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - name: Create Bazel output base directory
        run: |
          sudo mkdir -p /mnt/.bazel
          sudo chown -R $USER:$USER /mnt/.bazel
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          output-base: /mnt/.bazel
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
          # Cache external/
          external-cache: true
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - run: df -h
      - name: Bazel build targets
        run: |
          bazel build //...
      - run: df -h
        if: always()
      - name: Bazel test targets
        run: |
          bazel test //... --build_tests_only
      - run: df -h
        if: always()
